Use double brackets in Dockerfile

diff --git a/modules/tls-scripts/Dockerfile b/modules/tls-scripts/Dockerfile
--- a/modules/tls-scripts/Dockerfile
+++ b/modules/tls-scripts/Dockerfile
@@ -11,7 +11,7 @@ MAINTAINER Gruntwork "gruntwork.io"
 ARG GITHUB_OAUTH_TOKEN
 
 # If the build-time args are not defined, make it clear to the user.
-RUN if [ -z "$GITHUB_OAUTH_TOKEN" ]; then echo "ERROR: You must set GITHUB_OAUTH_TOKEN as a Docker build arg."; exit 1; fi
+RUN if [[ -z "$GITHUB_OAUTH_TOKEN" ]]; then echo "ERROR: You must set GITHUB_OAUTH_TOKEN as a Docker build arg."; exit 1; fi
 
 # Install dependencies
 RUN apt-get update && apt-get install -y \
